FROM python:3.14-slim AS builder

WORKDIR /app
COPY requirements.txt .

## install package to /root/.local
RUN pip install --user --no-cache-dir -r requirements.txt

FROM python:3.14-slim

WORKDIR /app


RUN useradd --create-home --shell /usr/sbin/nologin appuser
## copy package to appuser path and change owner as appuser
COPY --from=builder --chown=appuser:appuser /root/.local /home/appuser/.local
COPY app.py .

RUN chown -R appuser:appuser /app
# RUN chown -R appuser:appuser /home/appuser

USER appuser

## gunicorn look after PATH to run app.py
ENV PATH=/home/appuser/.local/bin:$path

HEALTHCHECK --interval=30s --timeout=5s --start-period=5s --retries=3 \
    CMD python -c "import urllib.request, urllib.request.urlopen('http://127.0.0.1/healthz')" || exit 1

CMD ["gunicorn", "--bind", "0.0.0.0:8080", "app:app"]

